In [1]:
import os
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

import numpy as np
import torch

print("Python environment is ready")
print("PyTorch version:", torch.__version__)

Python environment is ready
PyTorch version: 2.14.0+cpu


# LÀM QUEN VỚI PYTORCH

## Bài 1. Tạo Tensor cơ bản

In [2]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)
print(a)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [3]:

print("Kich thuoc (shape):", a.shape)
print("So chieu (ndim):", a.ndim)
print("Kieu du lieu (dtype):", a.dtype)


Kich thuoc (shape): torch.Size([2, 3])
So chieu (ndim): 2
Kieu du lieu (dtype): torch.int32


## Bài 2. Tạo các Tensor thường dùng

In [4]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.0704, 0.9000, 0.1193, 0.6111],
        [0.4234, 0.3320, 0.1512, 0.0898],
        [0.8689, 0.1769, 0.1956, 0.6113]])
tensor([[ 2.9080, -0.5149,  1.1360, -1.3436],
        [ 0.2478,  0.5073,  1.7610, -0.3877],
        [ 0.2982, -1.5654, -0.8820,  0.5545]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [5]:

f = torch.full((5, 5), 10)
print(f)


tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor

In [6]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)


Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Bài 4. Slicing và Indexing

In [7]:
import torch

torch.manual_seed(0)
a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])


Original tensor:
tensor([[[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487],
         [ 0.6920, -0.3160, -2.1152,  0.3223, -1.2633],
         [ 0.3500,  0.3081,  0.1198,  1.2377,  1.1168],
         [-0.2473, -1.3527, -1.6959,  0.5667,  0.7935]],

        [[ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502],
         [-0.5855, -0.1734,  0.1835,  1.3894,  1.5863],
         [ 0.9463, -0.8437, -0.6136,  0.0316, -0.4927],
         [ 0.2484,  0.4397,  0.1124,  0.6408,  0.4412]],

        [[-0.1023,  0.7924, -0.2897,  0.0525,  0.5943],
         [ 1.5419,  0.5073, -0.5910, -0.5692,  0.9200],
         [ 1.1108,  1.2899, -1.4959, -0.1938,  0.4455],
         [ 1.3253, -1.6293, -0.5497, -0.4798, -0.4997]]])

Tensor a[1]:
tensor([[ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502],
        [-0.5855, -0.1734,  0.1835,  1.3894,  1.5863],
        [ 0.9463, -0.8437, -0.6136,  0.0316, -0.4927],
        [ 0.2484,  0.4397,  0.1124,  0.6408,  0.4412]])

Tensor a[1:, 2:4]:
tensor([[[ 0.9463, -0.8437, -0.6136,  0.0316, -0.4

In [8]:

print("Shape a[1]:", a[1].shape)
print("Shape a[1:, 2:4]:", a[1:, 2:4].shape)
print("\nHai phan tu cuoi tren chieu thu 3 (a[..., -2:]):")
print(a[..., -2:])


Shape a[1]: torch.Size([4, 5])
Shape a[1:, 2:4]: torch.Size([2, 2, 5])

Hai phan tu cuoi tren chieu thu 3 (a[..., -2:]):
tensor([[[-0.4339,  0.8487],
         [ 0.3223, -1.2633],
         [ 1.2377,  1.1168],
         [ 0.5667,  0.7935]],

        [[ 1.8530,  0.7502],
         [ 1.3894,  1.5863],
         [ 0.0316, -0.4927],
         [ 0.6408,  0.4412]],

        [[ 0.0525,  0.5943],
         [-0.5692,  0.9200],
         [-0.1938,  0.4455],
         [-0.4798, -0.4997]]])


## Bài 5. Reshape và Flatten

In [9]:
import torch

torch.manual_seed(0)
a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))


Original:
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

Flatten:
tensor([ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033,  0.8380,
        -0.7193, -0.4033, -0.5966,  0.1820])

Reshape to 3 x 2 x 2:
tensor([[[ 1.5410, -0.2934],
         [-2.1788,  0.5684]],

        [[-1.0845, -1.3986],
         [ 0.4033,  0.8380]],

        [[-0.7193, -0.4033],
         [-0.5966,  0.1820]]])


In [10]:

print("So phan tu ban dau:", a.numel())
print("So phan tu sau flatten:", a.ravel().numel())
print("So phan tu sau reshape(3,2,2):", a.reshape(3, 2, 2).numel())

b = a.reshape(2, 6)
print("\nReshape thanh 2 x 6:")
print(b)


So phan tu ban dau: 12
So phan tu sau flatten: 12
So phan tu sau reshape(3,2,2): 12

Reshape thanh 2 x 6:
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820]])


## Bài 6. Phép toán và nhân ma trận

In [11]:
import torch

torch.manual_seed(0)
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)


a:
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])
b:
tensor([[ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]])

a + b:
tensor([[ 1.9443,  0.5446, -2.8980],
        [ 0.1651, -1.6812, -1.2166]])

a / b:
tensor([[ 3.8205, -0.3501,  3.0292],
        [-1.4093,  1.8177, -7.6831]])

a^2:
tensor([[2.3747, 0.0861, 4.7471],
        [0.3231, 1.1762, 1.9561]])

Matrix multiplication:
tensor([[ 1.9428, -0.8431],
        [ 0.3264,  0.1632]])


In [12]:

print("a * b (phan tu - phan tu):")
print(a * b)
print("\na @ b.T (nhan ma tran):")
print(a @ b.T)
print("\nShape cua a @ b.T:", (a @ b.T).shape)


a * b (phan tu - phan tu):
tensor([[ 0.6216, -0.2459,  1.5671],
        [-0.2293,  0.6471, -0.2546]])

a @ b.T (nhan ma tran):
tensor([[ 1.9428, -0.8431],
        [ 0.3264,  0.1632]])

Shape cua a @ b.T: torch.Size([2, 2])


## Bài 7. Các hàm thống kê trên Tensor

In [13]:
import torch

torch.manual_seed(0)
a = torch.randn(3, 4)
print(a)

print("\nMean (dim=0):")
print(torch.mean(a, dim=0))

print("\nStandard deviation (dim=0):")
print(torch.std(a, dim=0))

print("\nCumulative sum (dim=0):")
print(torch.cumsum(a, dim=0))


tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

Mean (dim=0):
tensor([-0.0876, -0.6985, -0.7907,  0.5295])

Standard deviation (dim=0):
tensor([1.4222, 0.6088, 1.3020, 0.3297])

Cumulative sum (dim=0):
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [ 0.4565, -1.6920, -1.7754,  1.4065],
        [-0.2628, -2.0954, -2.3721,  1.5885]])


In [14]:

print("Mean (dim=1):")
print(torch.mean(a, dim=1))

print("\nStandard deviation (dim=1):")
print(torch.std(a, dim=1))

print("\nCumulative sum (dim=1):")
print(torch.cumsum(a, dim=1))


Mean (dim=1):
tensor([-0.0907, -0.3104, -0.3843])

Standard deviation (dim=1):
tensor([1.5809, 1.0972, 0.3993])

Cumulative sum (dim=1):
tensor([[ 1.5410,  1.2476, -0.9312, -0.3628],
        [-1.0845, -2.4831, -2.0798, -1.2417],
        [-0.7193, -1.1226, -1.7192, -1.5372]])


## Bài 8. Autograd cơ bản

In [15]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)


x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [16]:

dy_dx_thu_cong = 2 * 3.6
print("Dao ham thu cong (2x tai x=3.6):", dy_dx_thu_cong)
print("x.grad (tu autograd):", x.grad.item())


Dao ham thu cong (2x tai x=3.6): 7.2
x.grad (tu autograd): 7.199999809265137


In [17]:

x2 = torch.tensor(3.6, requires_grad=True)
y2 = 3 * x2 ** 2 + 2 * x2 + 1
y2.backward()

print("x2 =", x2)
print("y2 =", y2)
print("x2.grad =", x2.grad)

dy2_dx_thu_cong = 6 * 3.6 + 2
print("Dao ham thu cong (6x+2 tai x=3.6):", dy2_dx_thu_cong)


x2 = tensor(3.6000, requires_grad=True)
y2 = tensor(47.0800, grad_fn=<AddBackward0>)
x2.grad = tensor(23.6000)
Dao ham thu cong (6x+2 tai x=3.6): 23.6


## Bài 9. Gradient Descent tìm hệ số đa thức

In [18]:
import numpy as np
import torch

np.random.seed(0)
polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.8567],
        [ 1.1006],
        [-1.0712]], requires_grad=True)
Learned coefficients:
tensor([[0.9605],
        [2.6126],
        [1.2582]], requires_grad=True)


In [19]:

print("He so mong muon: [1, 2, 3]")
print("He so hoc duoc:")
print(w.detach().numpy().ravel())


He so mong muon: [1, 2, 3]
He so hoc duoc:
[0.96048105 2.6125786  1.2582381 ]


## Bài 10. Giải hệ phương trình bằng Autograd

In [20]:
import random
import torch

random.seed(0)
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)


A = tensor(4.5494, requires_grad=True)
B = tensor(4.4506, requires_grad=True)
C = tensor(3.4506, requires_grad=True)
D = tensor(2.4506, requires_grad=True)


In [21]:

print("A + B =", (A + B).item(), " (mong muon 9)")
print("C - D =", (C - D).item(), " (mong muon 1)")
print("A + C =", (A + C).item(), " (mong muon 8)")
print("B - D =", (B - D).item(), " (mong muon 2)")


A + B = 8.99995231628418  (mong muon 9)
C - D = 1.0000104904174805  (mong muon 1)
A + C = 7.999969005584717  (mong muon 8)
B - D = 1.9999933242797852  (mong muon 2)


## Bài 11. Bài tập áp dụng

In [22]:

import torch

X = torch.arange(24)
print("X ban dau:", X, " shape:", X.shape)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nReshape 4x6:")
print(X_4x6)
print("\nReshape 2x12:")
print(X_2x12)
print("\nReshape 2x3x4:")
print(X_2x3x4)


X ban dau: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])  shape: torch.Size([24])

Reshape 4x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2x12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2x3x4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [23]:

torch.manual_seed(1)
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A:")
print(A)
print("B:")
print(B)

print("\nA + B:")
print(A + B)
print("\nA * B:")
print(A * B)
print("\nA / B:")
print(A / B)

print("\nTrung binh theo cot (dim=0):")
print(torch.mean(A, dim=0))
print("\nDo lech chuan theo cot (dim=0):")
print(torch.std(A, dim=0))


A:
tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
        [-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])
B:
tensor([[-0.1955, -0.9656,  0.4224,  0.2673],
        [-0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770]])

A + B:
tensor([[ 0.4658, -0.6987,  0.4841,  0.8886],
        [-0.8731, -0.6768, -3.0954,  0.2584],
        [ 2.5594, -2.3943,  0.7064, -1.3353]])

A * B:
tensor([[-0.1293, -0.2578,  0.0261,  0.1661],
        [ 0.1903,  0.0848,  2.3948, -0.0470],
        [-3.6860,  1.0311, -1.4265,  0.0744]])

A / B:
tensor([[-3.3827, -0.2764,  0.1460,  2.3243],
        [ 1.0729,  0.3253,  0.9683, -3.0969],
        [-0.2865,  0.3075, -0.5581,  0.0456]])

Trung binh theo cot (dim=0):
tensor([-0.2727, -0.1541, -0.7845,  0.3149])

Do lech chuan theo cot (dim=0):
tensor([0.8586, 0.4151, 0.7977, 0.3447])


In [24]:

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x ** 2 + 5 * x + 3
y.backward()

print("y tai x=2:", y.item())
print("dy/dx (autograd):", x.grad.item())

dy_dx_thu_cong = 4 * 2 + 5  # dao ham: 4x + 5
print("dy/dx (thu cong, 4x+5 tai x=2):", dy_dx_thu_cong)


y tai x=2: 21.0
dy/dx (autograd): 13.0
dy/dx (thu cong, 4x+5 tai x=2): 13


In [25]:

import numpy as np
import torch

np.random.seed(0)
polynomial2 = np.poly1d([2, -3, 5])
N = 20

X2 = np.random.randn(N, 1) * 5
Y2 = polynomial2(X2)

XX2 = np.hstack([
    X2 * X2,
    X2,
    np.ones_like(X2)
])

w2 = torch.randn(3, 1, requires_grad=True)
x2t = torch.tensor(XX2, dtype=torch.float32)
y2t = torch.tensor(Y2, dtype=torch.float32)

optimizer2 = torch.optim.NAdam([w2], lr=0.01)

print("Initial coefficients:")
print(w2)

for epoch in range(1000):
    optimizer2.zero_grad()
    y_pred2 = x2t @ w2
    mse2 = torch.mean(torch.square(y2t - y_pred2))
    mse2.backward()
    optimizer2.step()

print("Learned coefficients:")
print(w2)
print("\nHe so mong muon: [2, -3, 5]")
print("He so hoc duoc:", w2.detach().numpy().ravel())


Initial coefficients:
tensor([[ 0.3255],
        [-0.4791],
        [ 1.3790]], requires_grad=True)


Learned coefficients:
tensor([[ 1.8252],
        [-1.1278],
        [ 3.4162]], requires_grad=True)

He so mong muon: [2, -3, 5]
He so hoc duoc: [ 1.8252361 -1.1277906  3.4162383]
